version: "3.8"
services:
  db:
    image: postgres
    container_name: pgdb
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: ultr
      POSTGRES_PASSWORD: Hotelproj
    volumes:
      - local_pgdata:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: er.acosta@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Hotelproj
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: